In [2]:
import numpy as np
from scipy.linalg import eig

In [5]:
T = np.mat("0.2 0.4 0.4;0.8 0.2 0.0;0.8 0.0 0.2")
w, vl, vr = eig(T, left=True)

In [6]:
T

matrix([[0.2, 0.4, 0.4],
        [0.8, 0.2, 0. ],
        [0.8, 0. , 0.2]])

In [7]:
w

array([ 1. +0.j, -0.6+0.j,  0.2+0.j])

In [8]:
vl

array([[ 0.81649658,  0.81649658,  0.        ],
       [ 0.40824829, -0.40824829, -0.70710678],
       [ 0.40824829, -0.40824829,  0.70710678]])

In [9]:
vr

array([[ 5.77350269e-01,  5.77350269e-01, -2.45326947e-17],
       [ 5.77350269e-01, -5.77350269e-01, -7.07106781e-01],
       [ 5.77350269e-01, -5.77350269e-01,  7.07106781e-01]])